/**
 * Trick Configuration
 * 
 * Defines all available tricks, their costs, and rewards.
 * Each trick level provides better rewards than the last.
 * 
 * THIS FILE WAS AUTO-GENERATED by calculate-trick-values.js
 * Generated: 2026-03-02T11:19:04.047Z
 * 
 * Scaling:
 * - Level 0→1: 10 seconds
 * - Level 98→99: 36,000 seconds (10 hours)
 * - Exponential growth rate: 1.087148
 */

export const TRICKS = [
  {
    "level": 0,
    "name": "Respond to Name",
    "cost": 0,
    "reward": {
      "kibble": 1
    },
    "kibbleValue": 1,
    "description": "The very first step - recognizing your own name!"
  },
  {
    "level": 1,
    "name": "Sit",
    "cost": 10,
    "reward": {
      "kibble": 1
    },
    "kibbleValue": 1,
    "description": "The most basic trick - but every journey starts here!"
  },
  {
    "level": 2,
    "name": "Stay",
    "cost": 11,
    "reward": {
      "kibble": 1
    },
    "kibbleValue": 1,
    "description": "Patience is a virtue... and it pays in kibble."
  },
  {
    "level": 3,
    "name": "Down",
    "cost": 12,
    "reward": {
      "kibble": 2
    },
    "kibbleValue": 2,
    "description": "Low to the ground, high on rewards!"
  },
  {
    "level": 4,
    "name": "Come",
    "cost": 26,
    "reward": {
      "kibble": 2
    },
    "kibbleValue": 2,
    "description": "Coming when called - the mark of good training."
  },
  {
    "level": 5,
    "name": "Shake Paw",
    "cost": 28,
    "reward": {
      "kibble": 2
    },
    "kibbleValue": 2,
    "description": "A friendly greeting earns you kibble."
  },
  {
    "level": 6,
    "name": "Leave It",
    "cost": 30,
    "reward": {
      "kibble": 2
    },
    "kibbleValue": 2,
    "description": "Self-control is its own reward... plus kibble!"
  },
  {
    "level": 7,
    "name": "Heel",
    "cost": 33,
    "reward": {
      "kibble": 3
    },
    "kibbleValue": 3,
    "description": "Walking politely by your side."
  },
  {
    "level": 8,
    "name": "Roll Over",
    "cost": 54,
    "reward": {
      "kibble": 3
    },
    "kibbleValue": 3,
    "description": "A classic crowd-pleaser!"
  },
  {
    "level": 9,
    "name": "Play Dead",
    "cost": 59,
    "reward": {
      "kibble": 4
    },
    "kibbleValue": 4,
    "description": "Dramatic performance pays off."
  },
  {
    "level": 10,
    "name": "High Five",
    "cost": 85,
    "reward": {
      "kibble": 4
    },
    "kibbleValue": 4,
    "description": "So impressive you earn a Chicken Treat!"
  },
  {
    "level": 11,
    "name": "Spin Around",
    "cost": 92,
    "reward": {
      "kibble": 5
    },
    "kibbleValue": 5,
    "description": "A dizzying display of skill."
  },
  {
    "level": 12,
    "name": "Bow",
    "cost": 125,
    "reward": {
      "kibble": 5
    },
    "kibbleValue": 5,
    "description": "Take a bow - you earned it!"
  },
  {
    "level": 13,
    "name": "Crawl",
    "cost": 136,
    "reward": {
      "kibble": 6
    },
    "kibbleValue": 6,
    "description": "Commando-style movement for stealth kibble."
  },
  {
    "level": 14,
    "name": "Back Up",
    "cost": 178,
    "reward": {
      "kibble": 7
    },
    "kibbleValue": 7,
    "description": "Going in reverse - harder than it looks!"
  },
  {
    "level": 15,
    "name": "Touch Target",
    "cost": 225,
    "reward": {
      "kibble": 8
    },
    "kibbleValue": 8,
    "description": "Precision nose-booping!"
  },
  {
    "level": 16,
    "name": "Fetch Ball",
    "cost": 280,
    "reward": {
      "kibble": 9
    },
    "kibbleValue": 9,
    "description": "The classic game, now monetized!"
  },
  {
    "level": 17,
    "name": "Speak",
    "cost": 343,
    "reward": {
      "kibble": 11
    },
    "kibbleValue": 11,
    "description": "Use your voice for profit!"
  },
  {
    "level": 18,
    "name": "Quiet",
    "cost": 455,
    "reward": {
      "kibble": 12
    },
    "kibbleValue": 12,
    "description": "Sometimes silence is golden... and meaty!"
  },
  {
    "level": 19,
    "name": "Take It",
    "cost": 540,
    "reward": {
      "kibble": 14
    },
    "kibbleValue": 14,
    "description": "Gently accepting objects like a professional."
  },
  {
    "level": 20,
    "name": "Drop It",
    "cost": 685,
    "reward": {
      "chickenTreats": 1,
      "kibble": 6
    },
    "kibbleValue": 16,
    "description": "Letting go has never been more rewarding."
  },
  {
    "level": 21,
    "name": "Go to Bed",
    "cost": 851,
    "reward": {
      "chickenTreats": 1,
      "kibble": 9
    },
    "kibbleValue": 19,
    "description": "Self-bedtime for good dogs!"
  },
  {
    "level": 22,
    "name": "Ring Bell",
    "cost": 1099,
    "reward": {
      "chickenTreats": 2,
      "kibble": 2
    },
    "kibbleValue": 22,
    "description": "Ding dong! Service, please!"
  },
  {
    "level": 23,
    "name": "Find Keys",
    "cost": 1383,
    "reward": {
      "chickenTreats": 2,
      "kibble": 5
    },
    "kibbleValue": 25,
    "description": "Never lose your keys again!"
  },
  {
    "level": 24,
    "name": "Fetch Newspaper",
    "cost": 1708,
    "reward": {
      "chickenTreats": 2,
      "kibble": 9
    },
    "kibbleValue": 29,
    "description": "Useful AND adorable!"
  },
  {
    "level": 25,
    "name": "Close Door",
    "cost": 2154,
    "reward": {
      "chickenTreats": 3,
      "kibble": 3
    },
    "kibbleValue": 33,
    "description": "No more drafts in the house!"
  },
  {
    "level": 26,
    "name": "Turn Off Light",
    "cost": 2665,
    "reward": {
      "chickenTreats": 3,
      "kibble": 8
    },
    "kibbleValue": 38,
    "description": "Energy-efficient good boy!"
  },
  {
    "level": 27,
    "name": "Bring Leash",
    "cost": 3337,
    "reward": {
      "chickenTreats": 4,
      "kibble": 4
    },
    "kibbleValue": 44,
    "description": "Self-initiated walk time!"
  },
  {
    "level": 28,
    "name": "Tidy Toys",
    "cost": 4200,
    "reward": {
      "chickenTreats": 5
    },
    "kibbleValue": 50,
    "description": "A clean room is a happy room!"
  },
  {
    "level": 29,
    "name": "Army Crawl",
    "cost": 5189,
    "reward": {
      "chickenTreats": 5,
      "kibble": 8
    },
    "kibbleValue": 58,
    "description": "Military-grade stealth maneuvers!"
  },
  {
    "level": 30,
    "name": "Figure 8 Weaving",
    "cost": 6543,
    "reward": {
      "chickenTreats": 6,
      "kibble": 6
    },
    "kibbleValue": 66,
    "description": "Threading through legs like a pro!"
  },
  {
    "level": 31,
    "name": "Jump Through Hoop",
    "cost": 8095,
    "reward": {
      "chickenTreats": 7,
      "kibble": 6
    },
    "kibbleValue": 76,
    "description": "Circus-worthy aerial acrobatics!"
  },
  {
    "level": 32,
    "name": "Weave Poles",
    "cost": 10134,
    "reward": {
      "chickenTreats": 8,
      "kibble": 8
    },
    "kibbleValue": 88,
    "description": "Slalom champion in the making!"
  },
  {
    "level": 33,
    "name": "Open Door",
    "cost": 12756,
    "reward": {
      "steakTreats": 1,
      "kibble": 1
    },
    "kibbleValue": 101,
    "description": "No more waiting to be let in!"
  },
  {
    "level": 34,
    "name": "Retrieve Phone",
    "cost": 15917,
    "reward": {
      "steakTreats": 1,
      "chickenTreats": 1,
      "kibble": 6
    },
    "kibbleValue": 116,
    "description": "Never miss a call again!"
  },
  {
    "level": 35,
    "name": "Find Remote",
    "cost": 19874,
    "reward": {
      "steakTreats": 1,
      "chickenTreats": 3,
      "kibble": 3
    },
    "kibbleValue": 133,
    "description": "Lost remote? Not anymore!"
  },
  {
    "level": 36,
    "name": "Balance Treat",
    "cost": 24772,
    "reward": {
      "steakTreats": 1,
      "chickenTreats": 5,
      "kibble": 3
    },
    "kibbleValue": 153,
    "description": "Nose balancing mastery!"
  },
  {
    "level": 37,
    "name": "Dance Routine",
    "cost": 30980,
    "reward": {
      "steakTreats": 1,
      "chickenTreats": 7,
      "kibble": 6
    },
    "kibbleValue": 176,
    "description": "Your moves earn you premium treats!"
  },
  {
    "level": 38,
    "name": "Backflip",
    "cost": 38743,
    "reward": {
      "steakTreats": 2,
      "kibble": 3
    },
    "kibbleValue": 203,
    "description": "A spectacular acrobatic feat!"
  },
  {
    "level": 39,
    "name": "Walk on Hind Legs",
    "cost": 48581,
    "reward": {
      "steakTreats": 2,
      "chickenTreats": 3,
      "kibble": 3
    },
    "kibbleValue": 233,
    "description": "Bipedal brilliance!"
  },
  {
    "level": 40,
    "name": "Stack Blocks",
    "cost": 60620,
    "reward": {
      "kibble": 3
    },
    "kibbleValue": 268,
    "description": "Architectural dog engineering!"
  },
  {
    "level": 41,
    "name": "Sort Laundry",
    "cost": 75803,
    "reward": {
      "kibble": 3
    },
    "kibbleValue": 308,
    "description": "Whites separate from colors, obviously!"
  },
  {
    "level": 42,
    "name": "Push Shopping Cart",
    "cost": 94709,
    "reward": {
      "kibble": 4
    },
    "kibbleValue": 354,
    "description": "Grocery shopping assistant!"
  },
  {
    "level": 43,
    "name": "Answer Doorbell",
    "cost": 118340,
    "reward": {
      "kibble": 4
    },
    "kibbleValue": 407,
    "description": "Better than any butler!"
  },
  {
    "level": 44,
    "name": "Detect Allergies",
    "cost": 147915,
    "reward": {
      "kibble": 5
    },
    "kibbleValue": 468,
    "description": "Medical assistance dog!"
  },
  {
    "level": 45,
    "name": "Guide Blind Person",
    "cost": 184907,
    "reward": {
      "kibble": 5
    },
    "kibbleValue": 539,
    "description": "Professional service dog certification!"
  },
  {
    "level": 46,
    "name": "Skateboard",
    "cost": 231518,
    "reward": {
      "kibble": 6
    },
    "kibbleValue": 620,
    "description": "Radical shredding on four paws!"
  },
  {
    "level": 47,
    "name": "Surf",
    "cost": 289519,
    "reward": {
      "kibble": 7
    },
    "kibbleValue": 713,
    "description": "Catching waves and treats!"
  },
  {
    "level": 48,
    "name": "Play Piano",
    "cost": 361962,
    "reward": {
      "kibble": 8
    },
    "kibbleValue": 819,
    "description": "Mozart has nothing on you!"
  },
  {
    "level": 49,
    "name": "Paint Portrait",
    "cost": 452008,
    "reward": {
      "kibble": 9
    },
    "kibbleValue": 942,
    "description": "Abstract expressionist masterpiece!"
  },
  {
    "level": 50,
    "name": "Solve Puzzle",
    "cost": 565200,
    "reward": {
      "baconStrips": 1
    },
    "kibbleValue": 1084,
    "description": "500-piece jigsaw? Easy!"
  },
  {
    "level": 51,
    "name": "Tightrope Walk",
    "cost": 707081,
    "reward": {
      "baconStrips": 1
    },
    "kibbleValue": 1246,
    "description": "Death-defying balance act!"
  },
  {
    "level": 52,
    "name": "Juggle",
    "cost": 883582,
    "reward": {
      "baconStrips": 1
    },
    "kibbleValue": 1433,
    "description": "Three balls, no hands, all skill!"
  },
  {
    "level": 53,
    "name": "Magic Tricks",
    "cost": 1104750,
    "reward": {
      "baconStrips": 1
    },
    "kibbleValue": 1648,
    "description": "Now you see the treat, now you don't!"
  },
  {
    "level": 54,
    "name": "Card Counting",
    "cost": 1381223,
    "reward": {
      "baconStrips": 1
    },
    "kibbleValue": 1895,
    "description": "Vegas better watch out!"
  },
  {
    "level": 55,
    "name": "Speed Reading",
    "cost": 1726651,
    "reward": {
      "baconStrips": 2
    },
    "kibbleValue": 2180,
    "description": "1000 words per minute!"
  },
  {
    "level": 56,
    "name": "DJ Mixing",
    "cost": 2159437,
    "reward": {
      "baconStrips": 2
    },
    "kibbleValue": 2507,
    "description": "Dropping sick beats!"
  },
  {
    "level": 57,
    "name": "Gourmet Cooking",
    "cost": 2699773,
    "reward": {
      "baconStrips": 2
    },
    "kibbleValue": 2883,
    "description": "Michelin-starred chef!"
  },
  {
    "level": 58,
    "name": "Motorcycle Riding",
    "cost": 3375253,
    "reward": {
      "baconStrips": 3
    },
    "kibbleValue": 3315,
    "description": "Born to be wild!"
  },
  {
    "level": 59,
    "name": "Scuba Diving",
    "cost": 4219238,
    "reward": {
      "baconStrips": 3
    },
    "kibbleValue": 3812,
    "description": "Underwater exploration expert!"
  },
  {
    "level": 60,
    "name": "Parkour",
    "cost": 5274632,
    "reward": {
      "salmonFillets": 1
    },
    "kibbleValue": 4384,
    "description": "Urban acrobatics mastery!"
  },
  {
    "level": 61,
    "name": "Trapeze Artist",
    "cost": 6594754,
    "reward": {
      "salmonFillets": 1
    },
    "kibbleValue": 5042,
    "description": "Flying through the air with the greatest of ease!"
  },
  {
    "level": 62,
    "name": "Fire Breathing",
    "cost": 8245551,
    "reward": {
      "salmonFillets": 1
    },
    "kibbleValue": 5798,
    "description": "Hot dog takes on new meaning!"
  },
  {
    "level": 63,
    "name": "Sword Swallowing",
    "cost": 10308225,
    "reward": {
      "salmonFillets": 1
    },
    "kibbleValue": 6668,
    "description": "Not recommended for beginners!"
  },
  {
    "level": 64,
    "name": "Stunt Double",
    "cost": 12888134,
    "reward": {
      "salmonFillets": 1
    },
    "kibbleValue": 7668,
    "description": "Hollywood action star!"
  },
  {
    "level": 65,
    "name": "Opera Singing",
    "cost": 16112591,
    "reward": {
      "salmonFillets": 1
    },
    "kibbleValue": 8818,
    "description": "The Pavarotti of pups!"
  },
  {
    "level": 66,
    "name": "Stand-Up Comedy",
    "cost": 20143835,
    "reward": {
      "salmonFillets": 1
    },
    "kibbleValue": 10140,
    "description": "Who let the dogs out? This comedian!"
  },
  {
    "level": 67,
    "name": "Escape Artist",
    "cost": 25182499,
    "reward": {
      "salmonFillets": 1
    },
    "kibbleValue": 11662,
    "description": "The Houdini of hounds!"
  },
  {
    "level": 68,
    "name": "Tame Lions",
    "cost": 31486378,
    "reward": {
      "salmonFillets": 1
    },
    "kibbleValue": 13411,
    "description": "Who's the alpha now?"
  },
  {
    "level": 69,
    "name": "Wire Walking (Niagara Falls)",
    "cost": 39364037,
    "reward": {
      "salmonFillets": 1
    },
    "kibbleValue": 15422,
    "description": "One small step for dog, one giant leap for dogkind!"
  },
  {
    "level": 70,
    "name": "Shark Wrestling",
    "cost": 49211655,
    "reward": {
      "salmonFillets": 1
    },
    "kibbleValue": 17736,
    "description": "Jaws? More like paws!"
  },
  {
    "level": 71,
    "name": "Drive Car",
    "cost": 61527852,
    "reward": {
      "salmonFillets": 2
    },
    "kibbleValue": 20396,
    "description": "Paws on the wheel, eyes on the road!"
  },
  {
    "level": 72,
    "name": "Barrel Roll in Fighter Jet",
    "cost": 76921878,
    "reward": {
      "salmonFillets": 2
    },
    "kibbleValue": 23455,
    "description": "DO A BARREL ROLL! Top Gun has nothing on you!"
  },
  {
    "level": 73,
    "name": "Fly Drone",
    "cost": 96167674,
    "reward": {
      "salmonFillets": 2
    },
    "kibbleValue": 26974,
    "description": "Aerial surveillance specialist!"
  },
  {
    "level": 74,
    "name": "Hack Computer",
    "cost": 120234147,
    "reward": {
      "salmonFillets": 3
    },
    "kibbleValue": 31020,
    "description": "Cyber security? More like cyber pawrity!"
  },
  {
    "level": 75,
    "name": "Day Trading",
    "cost": 150318720,
    "reward": {
      "salmonFillets": 3
    },
    "kibbleValue": 35673,
    "description": "Wolf of Wall Street? Try Dog of Wall Street!"
  },
  {
    "level": 76,
    "name": "Compose Symphony",
    "cost": 187931557,
    "reward": {
      "salmonFillets": 4
    },
    "kibbleValue": 41024,
    "description": "Beethoven's 10th Symphony in K9 Major!"
  },
  {
    "level": 77,
    "name": "Speak 10 Languages",
    "cost": 234956185,
    "reward": {
      "salmonFillets": 4
    },
    "kibbleValue": 47177,
    "description": "Polyglot pup extraordinaire!"
  },
  {
    "level": 78,
    "name": "Sail Yacht",
    "cost": 293743320,
    "reward": {
      "salmonFillets": 5
    },
    "kibbleValue": 54254,
    "description": "Captain of the seven seas!"
  },
  {
    "level": 79,
    "name": "Defuse Bomb",
    "cost": 367246989,
    "reward": {
      "salmonFillets": 6
    },
    "kibbleValue": 62392,
    "description": "The hero we need!"
  },
  {
    "level": 80,
    "name": "Run Marathon (2hr)",
    "cost": 459139005,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 71751,
    "description": "Breaking world records on four legs!"
  },
  {
    "level": 81,
    "name": "Pilot Helicopter",
    "cost": 574026630,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 82514,
    "description": "Rotor wash never felt so good!"
  },
  {
    "level": 82,
    "name": "Perform Surgery",
    "cost": 717662947,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 94891,
    "description": "Doctor Dog, MD at your service!"
  },
  {
    "level": 83,
    "name": "Argue Supreme Court Case",
    "cost": 897236036,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 109124,
    "description": "Objection, your Honor! That's ruff!"
  },
  {
    "level": 84,
    "name": "Design Skyscraper",
    "cost": 1121736269,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 125493,
    "description": "Frank Lloyd Woof!"
  },
  {
    "level": 85,
    "name": "Quantum Computing",
    "cost": 1402422232,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 144317,
    "description": "Superposition of sit and stay simultaneously!"
  },
  {
    "level": 86,
    "name": "Peace Treaty Negotiation",
    "cost": 1753337735,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 165964,
    "description": "Nobel Peace Prize incoming!"
  },
  {
    "level": 87,
    "name": "Discover New Element",
    "cost": 2192051645,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 190859,
    "description": "Element 119: Dogonium!"
  },
  {
    "level": 88,
    "name": "Win Olympic Gold Medal",
    "cost": 2740553808,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 219488,
    "description": "All 50 events, naturally!"
  },
  {
    "level": 89,
    "name": "Direct Blockbuster Movie",
    "cost": 3426299096,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 252411,
    "description": "And the Oscar goes to..."
  },
  {
    "level": 90,
    "name": "Cure Disease",
    "cost": 4283626227,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 290272,
    "description": "Medical miracle worker!"
  },
  {
    "level": 91,
    "name": "Climb Mount Everest",
    "cost": 5355465647,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 333813,
    "description": "Without oxygen, because you're that good!"
  },
  {
    "level": 92,
    "name": "Deep Sea Exploration",
    "cost": 6695517344,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 383885,
    "description": "Mariana Trench? More like Marinara lunch!"
  },
  {
    "level": 93,
    "name": "Terraform Mars",
    "cost": 8370874625,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 441468,
    "description": "Making the red planet habitable, one paw at a time!"
  },
  {
    "level": 94,
    "name": "Invent Warp Drive",
    "cost": 10465445602,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 507688,
    "description": "Faster than light travel achieved!"
  },
  {
    "level": 95,
    "name": "Contact Alien Life",
    "cost": 13084110250,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 583841,
    "description": "First contact protocol: offer treats!"
  },
  {
    "level": 96,
    "name": "Time Travel",
    "cost": 16358018219,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 671418,
    "description": "Yesterday, today, and tomorrow - all at once!"
  },
  {
    "level": 97,
    "name": "Create Pocket Universe",
    "cost": 20451156812,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 772130,
    "description": "Your own reality where every day is walk day!"
  },
  {
    "level": 98,
    "name": "Master Teleportation",
    "cost": 25568433822,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 887950,
    "description": "Beam me up, Scotty - I mean, owner!"
  },
  {
    "level": 99,
    "name": "Ascend to Godhood",
    "cost": 31966200000,
    "reward": {
      "dragonFruit": 1
    },
    "kibbleValue": 1021142,
    "description": "The ultimate achievement - transcend reality itself and become a divine being!"
  }
];

/**
 * Reward type values in kibble
 */
export const REWARD_VALUES = {
  "kibble": 1,
  "chickenTreats": 10,
  "steakTreats": 100,
  "baconStrips": 1000,
  "salmonFillets": 10000,
  "lambChops": 50000,
  "goldenBones": 100000,
  "dragonFruit": 1000000,
  "unicornKibble": 5000000,
  "phoenixFeathers": 10000000,
  "cosmicCookies": 100000000,
  "celestialChews": 500000000,
  "quantumBiscuits": 1000000000,
  "infinityTreats": 10000000000,
  "singularitySnacks": 100000000000
};

/**
 * Get trick by level
 */
export function getTrickByLevel(level) {
  return TRICKS.find(trick => trick.level === level) || TRICKS[0];
}

/**
 * Get next trick for a given level
 */
export function getNextTrick(currentLevel) {
  return TRICKS.find(trick => trick.level === currentLevel + 1);
}

/**
 * Check if max level reached
 */
export function isMaxLevel(level) {
  return level >= TRICKS.length - 1;
}

/**
 * Calculate total kibble value from a reward object
 */
export function calculateRewardValue(reward) {
  let total = 0;
  for (const [type, amount] of Object.entries(reward)) {
    total += (REWARD_VALUES[type] || 0) * amount;
  }
  return total;
}
